parameters:
#    gyouth_home.example.class: Gyouth\Bundle\HomeBundle\Example

services:
#    gyouth_home.example:
#        class: %gyouth_home.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
